language: php
php: 5.5
env:
  global:
  - J2P_AWS_REGION="us-east-1"
sudo: false
before_script:
- composer self-update
- composer install
addons:
  ssh_known_hosts:
  - https://dynamodb.us-east-1.amazonaws.com/
  - https://dynamodb.us-west-2.amazonaws.com/

